sudo: false
language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"

addons:
  firefox: latest-beta

before_install:
 - "export DISPLAY=:99.0"
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"

before_script:
  - npm install grunt-cli -g

script:
  - export FIREFOX_BIN=`which firefox`
  - npm test
